#jwt:
#    secretKey: asdfkasdf89as7dfasd9fyuakjshdfa87sdf8iasuhfjas9d8f7as8idfuhjasd89f7asdi8fu
#
#spring:
#  application:
#    name: api-gateway
#
#    #api gateway config
#  cloud:
#    gateway:
#      server:
##         webmvc:
#        webflux:
#          routes:
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
##                 - Path=/orders/**
#                - Path=/api/v1/orders/**
#              filters:
#                - StripPrefix=2
##                 - RedirectTo=302, http://codingshuttle.com
#                - name: LoggingOrdersFilter
#                - name: Authentication
#                  args:
##                    isEnabled: true
#                    isEnabled: false
#            #   - name: Authorization
#            #     args:
#            #       allowedRoles: ADMIN, SUPER_ADMIN
#            - id: inventory-service
#              uri: lb://INVENTORY-SERVICE
#              predicates:
##                 - Path=/inventory/**
#                - Path=/api/v1/inventory/**
#              filters:
#                - StripPrefix=2
#                - name: Authentication
##                  - RedirectTo=302, http://codingshuttle.com
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888