spring.application.name: config-server
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jitu-77/ecommApp-config-server
          username: Jitu-77
          password: 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
          default-label: main
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka